### ISSUE TITLE
All modules installed but still errors

### ISSUE THREAD

**Issue by officialjakefromstatefarm** [DSJAS/DSJAS#82]
I've made sure that all modules were included in php.ini, but I still get the Minimum PHP Requirements Not Met error. I have also verified that they existed in /apache/bin.
OS: Windows 10
XAMPP Control Panel v3.30
DSJAS alpha v0.1.4
php.ini: https://pastebin.com/jf1bNwkK
apache error.log: https://pastebin.com/jedrLnm6
![Capture](https://github.com/DSJAS/DSJAS/assets/156488239/86fdae3b-92a5-450c-b979-f636e72e91a2)

**Comment by ejv2** [comment]
Hi @officialjakefromstatefarm, sorry you're having issues. Can you please download [this script](https://raw.githubusercontent.com/DSJAS/DSJAS/master/scripts/checkmods.php) and stick it on your server. Then, just navigate to "/checkmods.php" and post a screenshot of the output.

Chances are, you've done everything right but something isn't installed properly (this happens sometimes with XAMPP/MAMP).

**Comment by officialjakefromstatefarm** [comment]
This is the result
![Capture](https://github.com/DSJAS/DSJAS/assets/156488239/256a0be4-bb78-4d7a-9b3f-e1d549272ea8)
I made sure that Sodium was uncommented in php.ini and that it was in my folders. I could try reinstalling it but I couldn't find where to download it.
![Capture2](https://github.com/DSJAS/DSJAS/assets/156488239/6134e62c-d46a-4658-a37d-f097bcd5c483)

**Comment by ejv2** [comment]
I'm not entirely sure, but could you try copying the dll named "php_sodium.dll" into "C:\xampp\php\ext"? I've been told that is the location of extensions to PHP rather than the apache bin. If it still doesn't work, try renaming it back to the previous name and try again. Make sure you restart Apache between changes.

Again, sorry this is so confusing. I thought that sodium would be a reasonable dependency, as the [PHP docs say](https://www.php.net/manual/en/sodium.installation.php) that sodium is bundled by default since v7.2 (for reference, you are on 8.2 I think).

Hope this works for you!

**Comment by officialjakefromstatefarm** [comment]
I messed something up. I reinstalled xampp for another other issue and now it gives me this page when I go to localhost instead of an error or a bank. I used the same files as before.
![Capture](https://github.com/DSJAS/DSJAS/assets/156488239/2daa5119-29c1-4076-8f05-eabbf2c27bf4)
I think the sodium issue was fixed though, my error logs don't have the same "The specified module could not be found" error.

apache error.log https://pastebin.com/H8pQBk3A
php.ini https://pastebin.com/mUVarmfY

**Comment by ejv2** [comment]
Make sure you set the document root to the public directory, not the root of the site.

Also, your error logs show that sodium still isn't loading:

> PHP Warning:  PHP Startup: Unable to load dynamic library 'sodium' (tried: C:\\xampp\\php\\ext\\sodium (The specified module could not be found), C:\\xampp\\php\\ext\\php_sodium.dll (The specified module could not be found)) in Unknown on line 0

**Comment by GreenScambaits** [comment]
Hey I am getting the same error with modules missing and same red panel as image at top of this feed. I see you added a file to paste to the server but where should this be pasted ? In the php.ini folder? And added on to the end or replacing the existing text?

**Comment by ejv2** [comment]
@GreenScambaits Hi. You need to place that file into the same location that all the other DSJAS files are located (the public folder). Then, start your server and go to "/checkmods.php" in your browser. This will confirm which modules are not being loaded correctly.

**Comment by officialjakefromstatefarm** [comment]
It worked, but now I'm stuck on the database setup page. The confirm and setup button doesn't do anything. Clicking on the manual setup button gives me this
![Capture](https://github.com/DSJAS/DSJAS/assets/156488239/8afcf92d-1387-42b7-9dc0-d69acec04b07)

**Comment by ejv2** [comment]
Press where it says click here. It should place you back on the database setup screen. Try pressing "Test Configuration" before trying to save and see what result it gives you.

**Comment by officialjakefromstatefarm** [comment]
I get this. I dont know if there's supposed to be a redirect or something but clicking the confirm button only clears all the fields and refreshes the page
![Capture](https://github.com/DSJAS/DSJAS/assets/156488239/68314c36-e247-41a5-b6fe-37d774d2fd50)

This is also on the top of the page
![Capture2](https://github.com/DSJAS/DSJAS/assets/156488239/63290b58-b854-467f-b616-78743f1f15d7)

**Comment by ejv2** [comment]
Please post the contents of your Config.ini to a pastebin. This should be the last issue to solve before you're all sorted. It looks like your config got corrupted somehow.

**Comment by Trexgameroffical** [comment]
Im getting this same error and its installed properly

![image](https://github.com/DSJAS/DSJAS/assets/40707804/01216948-ca6d-4db0-bd17-fd6531d566a5)

**Comment by ejv2** [comment]
@Trexgameroffical Hello! If you're getting this error, things can't be installed properly. Please post your apache error log for me.

**Comment by ejv2** [comment]
On a general note for everybody, I will be publishing a new release soon which relaxes the requirement for sodium to be installed. I thought it was bundled with xampp and mamp, but given that it's caused this much trouble, I think it's probably worth rewriting the small bit of code that depends on it.

**Comment by officialjakefromstatefarm** [comment]
I couldn't find anything about config.ini, can you tell me the file path?
If you meant php.ini, here it is

https://pastebin.com/fcdSi8RA

**Comment by ejv2** [comment]
Your config.ini stores your DSJAS settings, not your PHP settings. It should be stored in the public folder along with the rest of the DSJAS files. If there isn't one present, download the default one [from here](https://raw.githubusercontent.com/DSJAS/DSJAS/master/scripts/install/Config.ini) and put it in the public directory. You'll need to restart the install process but everything should work fine after that.

**Comment by officialjakefromstatefarm** [comment]
https://pastebin.com/E0WcWaqV

**Comment by ejv2** [comment]
Ok that's missing quite a few fields. Try downloading the default one and replacing the contents.

**Comment by oscartopi** [comment]
> On a general note for everybody, I will be publishing a new release soon which relaxes the requirement for sodium to be installed. I thought it was bundled with xampp and mamp, but given that it's caused this much trouble, I think it's probably worth rewriting the small bit of code that depends on it.

Thanks, I really appreciate it, I can’t wait to finally be able to use it. That issue has been driving me nuts!

No matter what version of XAMPP, WAMP, MAMP I use, or downgrading php versions I can’t get past that missing sodium error. I’ve tried downloading the sodium.dll and even moving the lib file as well but it always returns the error unfortunately.

**Comment by ejv2** [comment]
@oscartopi @officialjakefromstatefarm I've just published v0.1.5 which drops the requirement for libsodium in the installer. If you're still having trouble, please download this release and give it a try. I'm going to close this issue now. If you have any further trouble, please feel free to re-open or create a new issue.
